---
- hosts: "{{ servidores }}"
  tasks:
  - name: crear directorio prueba WHEN
    win_file:
      path: c:\TEMP\prueba_when
      state: directory
    when: ansible_ip_addresses [0] == "192.168.17.202"