---
- hosts: "{{ servidores }}"
  gather_facts: false
  tasks:
    - name: Check Web Connection
      win_uri:
        url: "http://localhost"
      ignore_errors: true
    - name: "la tarea anterior ha ido bien"
      debug:
        msg: "la tarea es ok"